const ROLES = {
  ADMIN: 'ADMIN',
  SELLER: 'SELLER',
  USER: 'USER'
};

const PERMISSIONS = {
  CREATE_AUCTION: 'create:auction',
  MANAGE_AUCTION: 'manage:auction',
  PLACE_BID: 'place:bid',
  MANAGE_USERS: 'manage:users',
  VERIFY_SELLERS: 'verify:sellers',
  MANAGE_REPORTS: 'manage:reports'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_AUCTION,
    PERMISSIONS.MANAGE_AUCTION,
    PERMISSIONS.PLACE_BID,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VERIFY_SELLERS,
    PERMISSIONS.MANAGE_REPORTS
  ],
  [ROLES.SELLER]: [
    PERMISSIONS.CREATE_AUCTION,
    PERMISSIONS.MANAGE_AUCTION,
    PERMISSIONS.PLACE_BID
  ],
  [ROLES.USER]: [
    PERMISSIONS.PLACE_BID
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};