// @ts-nocheck

import {
  Eye,
  EyeOff,
  Loader2,
  Facebook,
  Mail,
  type Icon as LucideIcon,
  Eraser,
  Settings,
  Laptop,
  Shirt,
  User2,
  ArrowBigLeft,
  MoveLeft,
  Search,
  ChevronLeft,
  ChevronRight,
  ArrowUpDown,
  RefreshCcw,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  Asterisk,
  ArrowBigLeftDash,
  LogOut,
  Download,
  Clock,
  Ban,
  User,
  X,
  UserPlus,
  Copy,
  Trash,
  Play,
  StopCircle,
  Tag,
  DollarSign,
  AlertCircle,
  Edit,
  Box,
  Activity,
  CheckCircle,
  TrendingUp,
  TrendingDown,
  Calendar,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  clock: Clock,
  more: MoreHorizontal,
  users: User,
  calendar: Calendar,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  x: X,
  box: Box,
  activity: Activity,
  checkCircle: CheckCircle,
  userPlus: UserPlus,
  ban: Ban,
  play: Play,
  stop: StopCircle,
  tag: Tag,
  eye: Eye,
  eyeOff: EyeOff,
  spinner: Loader2,
  facebook: Facebook,
  google: Mail,
  mail: Mail,
  dollarSign: DollarSign,
  alertCircle: AlertCircle,
  error: Eraser,
  check: Settings,
  laptop: Laptop,
  shirt: Shirt,
  download: Download,
  user: User2,
  logout: LogOut,
  backBtn: MoveLeft,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUpDown: ArrowUpDown,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  refresh: RefreshCcw,
  moreHorizontal: MoreHorizontal,
  asterisk: Asterisk,
  ArrowBigLeftDash: ArrowBigLeftDash,
  moveLeft: MoveLeft,
  copy: Copy,
  edit: Edit,
  trash: Trash,
};
