import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from './providers';
import { LocationProvider } from '@/contexts/LocationContext';
import { Toaster } from '@/components/ui/toaster';

import { Suspense } from 'react';
import Loading from './loading';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Define the viewport configuration
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
  viewportFit: 'cover', // For better mobile responsiveness
  themeColor: '#ffffff', // Default theme color
};

// Define the metadata configuration
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {' '}
        <Providers>
          <LocationProvider>
            <Suspense fallback={<Loading />}>{children}</Suspense>
            <Toaster />
          </LocationProvider>
        </Providers>
      </body>
    </html>
  );
}
